"""
Interaction Handlers
Manages gaze-based interactions: hover, dwell selection, scroll, etc.
"""
import time
from typing import Optional, Callable, Dict, Any, List, Tuple
from dataclasses import dataclass
from enum import Enum


class InteractionType(Enum):
    HOVER = "hover"
    DWELL_SELECT = "dwell_select"
    BLINK_SELECT = "blink_select"
    SCROLL_UP = "scroll_up"
    SCROLL_DOWN = "scroll_down"
    NONE = "none"


@dataclass
class UIElement:
    """Represents a UI element that can receive gaze interactions"""
    id: str
    x: int
    y: int
    width: int
    height: int
    selectable: bool = True
    scrollable: bool = False
    metadata: Dict[str, Any] = None


@dataclass 
class InteractionEvent:
    """Event generated by interaction handler"""
    type: InteractionType
    element_id: Optional[str]
    x: int
    y: int
    timestamp: float
    duration_ms: float = 0
    metadata: Dict[str, Any] = None


class DwellTimer:
    """Tracks dwell time on elements for selection"""
    
    def __init__(self, threshold_ms: float = 800):
        self.threshold_ms = threshold_ms
        self.current_element: Optional[str] = None
        self.dwell_start: float = 0
        self.accumulated_time: float = 0
        
    def update(
        self,
        element_id: Optional[str],
        timestamp: float
    ) -> Optional[float]:
        """
        Update dwell tracking.
        
        Args:
            element_id: ID of element being gazed at (None if none)
            timestamp: Current timestamp in ms
            
        Returns:
            Progress (0-1) if dwelling, None if not dwelling
        """
        if element_id is None:
            self.reset()
            return None
        
        if element_id != self.current_element:
            # New element, restart dwell
            self.current_element = element_id
            self.dwell_start = timestamp
            self.accumulated_time = 0
            return 0.0
        
        # Same element, accumulate time
        self.accumulated_time = timestamp - self.dwell_start
        progress = min(1.0, self.accumulated_time / self.threshold_ms)
        
        return progress
    
    def is_complete(self) -> bool:
        """Check if dwell time threshold has been reached"""
        return self.accumulated_time >= self.threshold_ms
    
    def reset(self):
        """Reset dwell timer"""
        self.current_element = None
        self.dwell_start = 0
        self.accumulated_time = 0
    
    def get_element(self) -> Optional[str]:
        """Get current element being dwelled on"""
        return self.current_element


class ScrollHandler:
    """Handles gaze-based scrolling"""
    
    def __init__(
        self,
        threshold: float = 0.2,
        speed: float = 5.0,
        dead_zone: float = 0.3
    ):
        """
        Initialize scroll handler.
        
        Args:
            threshold: Gaze offset threshold to trigger scroll
            speed: Scroll speed multiplier
            dead_zone: Center dead zone (no scroll)
        """
        self.threshold = threshold
        self.speed = speed
        self.dead_zone = dead_zone
        self.scroll_region: Optional[UIElement] = None
        
    def update(
        self,
        gaze_y: float,
        region_y: int,
        region_height: int
    ) -> Tuple[InteractionType, float]:
        """
        Calculate scroll based on gaze position within region.
        
        Args:
            gaze_y: Current gaze Y coordinate
            region_y: Scroll region top Y
            region_height: Scroll region height
            
        Returns:
            (scroll_type, scroll_amount)
        """
        # Calculate relative position in region (0 = top, 1 = bottom)
        relative_y = (gaze_y - region_y) / region_height
        relative_y = max(0, min(1, relative_y))
        
        # Convert to centered (-0.5 to 0.5)
        centered = relative_y - 0.5
        
        # Check dead zone
        if abs(centered) < self.dead_zone / 2:
            return InteractionType.NONE, 0.0
        
        # Calculate scroll amount
        if centered < 0:
            # Looking at top = scroll up
            amount = (abs(centered) - self.dead_zone / 2) * self.speed
            return InteractionType.SCROLL_UP, amount
        else:
            # Looking at bottom = scroll down
            amount = (centered - self.dead_zone / 2) * self.speed
            return InteractionType.SCROLL_DOWN, amount


class InteractionHandler:
    """
    Main interaction handler for gaze-based UI interactions.
    Manages hover, dwell selection, blink selection, and scrolling.
    """
    
    def __init__(
        self,
        dwell_time_ms: float = 800,
        scroll_threshold: float = 0.2,
        scroll_speed: float = 5.0,
        hover_radius: int = 50
    ):
        """
        Initialize interaction handler.
        
        Args:
            dwell_time_ms: Time to gaze at element for selection
            scroll_threshold: Gaze offset for scroll trigger
            scroll_speed: Scroll speed multiplier
            hover_radius: Radius around gaze for hover detection
        """
        self.dwell_timer = DwellTimer(dwell_time_ms)
        self.scroll_handler = ScrollHandler(scroll_threshold, scroll_speed)
        self.hover_radius = hover_radius
        
        # Registered UI elements
        self.elements: Dict[str, UIElement] = {}
        
        # Current state
        self.hovered_element: Optional[str] = None
        self.last_selected: Optional[str] = None
        self.selection_cooldown_ms = 1000
        self.last_selection_time = 0
        
        # Event callbacks
        self.on_hover: Optional[Callable[[str], None]] = None
        self.on_hover_exit: Optional[Callable[[str], None]] = None
        self.on_select: Optional[Callable[[str], None]] = None
        self.on_scroll: Optional[Callable[[InteractionType, float], None]] = None
        
    def register_element(self, element: UIElement):
        """Register a UI element for interaction"""
        self.elements[element.id] = element
    
    def unregister_element(self, element_id: str):
        """Remove a UI element"""
        if element_id in self.elements:
            del self.elements[element_id]
    
    def clear_elements(self):
        """Remove all registered elements"""
        self.elements.clear()
        self.dwell_timer.reset()
        self.hovered_element = None
    
    def update(
        self,
        gaze_x: int,
        gaze_y: int,
        timestamp: float,
        blink_detected: bool = False
    ) -> List[InteractionEvent]:
        """
        Update interactions based on current gaze position.
        
        Args:
            gaze_x: Current gaze X coordinate
            gaze_y: Current gaze Y coordinate  
            timestamp: Current timestamp in ms
            blink_detected: Whether a blink was detected
            
        Returns:
            List of interaction events
        """
        events = []
        
        # Find element under gaze
        hit_element = self._hit_test(gaze_x, gaze_y)
        
        # Handle hover
        hover_event = self._handle_hover(hit_element, gaze_x, gaze_y, timestamp)
        if hover_event:
            events.append(hover_event)
        
        # Handle dwell selection
        if hit_element and self.elements[hit_element].selectable:
            dwell_event = self._handle_dwell(hit_element, gaze_x, gaze_y, timestamp)
            if dwell_event:
                events.append(dwell_event)
        else:
            self.dwell_timer.reset()
        
        # Handle blink selection
        if blink_detected and hit_element:
            blink_event = self._handle_blink_select(hit_element, gaze_x, gaze_y, timestamp)
            if blink_event:
                events.append(blink_event)
        
        # Handle scroll (check for scrollable elements)
        scroll_event = self._handle_scroll(gaze_x, gaze_y, timestamp)
        if scroll_event:
            events.append(scroll_event)
        
        return events
    
    def _hit_test(self, gaze_x: int, gaze_y: int) -> Optional[str]:
        """Find element under gaze point with hover radius"""
        for element_id, element in self.elements.items():
            # Expand hit area by hover radius
            if (element.x - self.hover_radius <= gaze_x <= element.x + element.width + self.hover_radius and
                element.y - self.hover_radius <= gaze_y <= element.y + element.height + self.hover_radius):
                return element_id
        return None
    
    def _handle_hover(
        self,
        element_id: Optional[str],
        gaze_x: int,
        gaze_y: int,
        timestamp: float
    ) -> Optional[InteractionEvent]:
        """Handle hover state changes"""
        if element_id != self.hovered_element:
            # Hover changed
            old_element = self.hovered_element
            self.hovered_element = element_id
            
            # Fire exit callback
            if old_element and self.on_hover_exit:
                self.on_hover_exit(old_element)
            
            # Fire enter callback and return event
            if element_id:
                if self.on_hover:
                    self.on_hover(element_id)
                
                return InteractionEvent(
                    type=InteractionType.HOVER,
                    element_id=element_id,
                    x=gaze_x,
                    y=gaze_y,
                    timestamp=timestamp
                )
        
        return None
    
    def _handle_dwell(
        self,
        element_id: str,
        gaze_x: int,
        gaze_y: int,
        timestamp: float
    ) -> Optional[InteractionEvent]:
        """Handle dwell-based selection"""
        # Check cooldown
        if timestamp - self.last_selection_time < self.selection_cooldown_ms:
            return None
        
        progress = self.dwell_timer.update(element_id, timestamp)
        
        if self.dwell_timer.is_complete():
            self.last_selection_time = timestamp
            self.last_selected = element_id
            self.dwell_timer.reset()
            
            if self.on_select:
                self.on_select(element_id)
            
            return InteractionEvent(
                type=InteractionType.DWELL_SELECT,
                element_id=element_id,
                x=gaze_x,
                y=gaze_y,
                timestamp=timestamp,
                duration_ms=self.dwell_timer.threshold_ms,
                metadata={"progress": 1.0}
            )
        
        return None
    
    def _handle_blink_select(
        self,
        element_id: str,
        gaze_x: int,
        gaze_y: int,
        timestamp: float
    ) -> Optional[InteractionEvent]:
        """Handle blink-based selection"""
        # Check cooldown
        if timestamp - self.last_selection_time < self.selection_cooldown_ms:
            return None
        
        element = self.elements.get(element_id)
        if not element or not element.selectable:
            return None
        
        self.last_selection_time = timestamp
        self.last_selected = element_id
        
        if self.on_select:
            self.on_select(element_id)
        
        return InteractionEvent(
            type=InteractionType.BLINK_SELECT,
            element_id=element_id,
            x=gaze_x,
            y=gaze_y,
            timestamp=timestamp
        )
    
    def _handle_scroll(
        self,
        gaze_x: int,
        gaze_y: int,
        timestamp: float
    ) -> Optional[InteractionEvent]:
        """Handle gaze-based scrolling"""
        # Find scrollable element under gaze
        for element_id, element in self.elements.items():
            if not element.scrollable:
                continue
            
            if (element.x <= gaze_x <= element.x + element.width and
                element.y <= gaze_y <= element.y + element.height):
                
                scroll_type, amount = self.scroll_handler.update(
                    gaze_y, element.y, element.height
                )
                
                if scroll_type != InteractionType.NONE:
                    if self.on_scroll:
                        self.on_scroll(scroll_type, amount)
                    
                    return InteractionEvent(
                        type=scroll_type,
                        element_id=element_id,
                        x=gaze_x,
                        y=gaze_y,
                        timestamp=timestamp,
                        metadata={"amount": amount}
                    )
        
        return None
    
    def get_dwell_progress(self) -> Tuple[Optional[str], float]:
        """Get current dwell progress for UI feedback"""
        if self.dwell_timer.current_element:
            progress = self.dwell_timer.accumulated_time / self.dwell_timer.threshold_ms
            return self.dwell_timer.current_element, min(1.0, progress)
        return None, 0.0
